import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-display-three',
  templateUrl: './display-three.component.html',
  styleUrls: ['./display-three.component.css']
})
export class DisplayThreeComponent implements OnInit {

  userData=[
  {
    "login": "tomtt",
    "id": 31,
    "node_id": "MDQ6VXNlcjMx",
    "avatar_url": "https://avatars.githubusercontent.com/u/31?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/tomtt",
    "html_url": "https://github.com/tomtt",
    "followers_url": "https://api.github.com/users/tomtt/followers",
    "following_url": "https://api.github.com/users/tomtt/following{/other_user}",
    "gists_url": "https://api.github.com/users/tomtt/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/tomtt/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/tomtt/subscriptions",
    "organizations_url": "https://api.github.com/users/tomtt/orgs",
    "repos_url": "https://api.github.com/users/tomtt/repos",
    "events_url": "https://api.github.com/users/tomtt/events{/privacy}",
    "received_events_url": "https://api.github.com/users/tomtt/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "railsjitsu",
    "id": 32,
    "node_id": "MDQ6VXNlcjMy",
    "avatar_url": "https://avatars.githubusercontent.com/u/32?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/railsjitsu",
    "html_url": "https://github.com/railsjitsu",
    "followers_url": "https://api.github.com/users/railsjitsu/followers",
    "following_url": "https://api.github.com/users/railsjitsu/following{/other_user}",
    "gists_url": "https://api.github.com/users/railsjitsu/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/railsjitsu/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/railsjitsu/subscriptions",
    "organizations_url": "https://api.github.com/users/railsjitsu/orgs",
    "repos_url": "https://api.github.com/users/railsjitsu/repos",
    "events_url": "https://api.github.com/users/railsjitsu/events{/privacy}",
    "received_events_url": "https://api.github.com/users/railsjitsu/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "nitay",
    "id": 34,
    "node_id": "MDQ6VXNlcjM0",
    "avatar_url": "https://avatars.githubusercontent.com/u/34?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/nitay",
    "html_url": "https://github.com/nitay",
    "followers_url": "https://api.github.com/users/nitay/followers",
    "following_url": "https://api.github.com/users/nitay/following{/other_user}",
    "gists_url": "https://api.github.com/users/nitay/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/nitay/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/nitay/subscriptions",
    "organizations_url": "https://api.github.com/users/nitay/orgs",
    "repos_url": "https://api.github.com/users/nitay/repos",
    "events_url": "https://api.github.com/users/nitay/events{/privacy}",
    "received_events_url": "https://api.github.com/users/nitay/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "kevwil",
    "id": 35,
    "node_id": "MDQ6VXNlcjM1",
    "avatar_url": "https://avatars.githubusercontent.com/u/35?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/kevwil",
    "html_url": "https://github.com/kevwil",
    "followers_url": "https://api.github.com/users/kevwil/followers",
    "following_url": "https://api.github.com/users/kevwil/following{/other_user}",
    "gists_url": "https://api.github.com/users/kevwil/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/kevwil/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/kevwil/subscriptions",
    "organizations_url": "https://api.github.com/users/kevwil/orgs",
    "repos_url": "https://api.github.com/users/kevwil/repos",
    "events_url": "https://api.github.com/users/kevwil/events{/privacy}",
    "received_events_url": "https://api.github.com/users/kevwil/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "KirinDave",
    "id": 36,
    "node_id": "MDQ6VXNlcjM2",
    "avatar_url": "https://avatars.githubusercontent.com/u/36?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/KirinDave",
    "html_url": "https://github.com/KirinDave",
    "followers_url": "https://api.github.com/users/KirinDave/followers",
    "following_url": "https://api.github.com/users/KirinDave/following{/other_user}",
    "gists_url": "https://api.github.com/users/KirinDave/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/KirinDave/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/KirinDave/subscriptions",
    "organizations_url": "https://api.github.com/users/KirinDave/orgs",
    "repos_url": "https://api.github.com/users/KirinDave/repos",
    "events_url": "https://api.github.com/users/KirinDave/events{/privacy}",
    "received_events_url": "https://api.github.com/users/KirinDave/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "jamesgolick",
    "id": 37,
    "node_id": "MDQ6VXNlcjM3",
    "avatar_url": "https://avatars.githubusercontent.com/u/37?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jamesgolick",
    "html_url": "https://github.com/jamesgolick",
    "followers_url": "https://api.github.com/users/jamesgolick/followers",
    "following_url": "https://api.github.com/users/jamesgolick/following{/other_user}",
    "gists_url": "https://api.github.com/users/jamesgolick/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jamesgolick/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jamesgolick/subscriptions",
    "organizations_url": "https://api.github.com/users/jamesgolick/orgs",
    "repos_url": "https://api.github.com/users/jamesgolick/repos",
    "events_url": "https://api.github.com/users/jamesgolick/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jamesgolick/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "atmos",
    "id": 38,
    "node_id": "MDQ6VXNlcjM4",
    "avatar_url": "https://avatars.githubusercontent.com/u/38?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/atmos",
    "html_url": "https://github.com/atmos",
    "followers_url": "https://api.github.com/users/atmos/followers",
    "following_url": "https://api.github.com/users/atmos/following{/other_user}",
    "gists_url": "https://api.github.com/users/atmos/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/atmos/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/atmos/subscriptions",
    "organizations_url": "https://api.github.com/users/atmos/orgs",
    "repos_url": "https://api.github.com/users/atmos/repos",
    "events_url": "https://api.github.com/users/atmos/events{/privacy}",
    "received_events_url": "https://api.github.com/users/atmos/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "errfree",
    "id": 44,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjQ0",
    "avatar_url": "https://avatars.githubusercontent.com/u/44?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/errfree",
    "html_url": "https://github.com/errfree",
    "followers_url": "https://api.github.com/users/errfree/followers",
    "following_url": "https://api.github.com/users/errfree/following{/other_user}",
    "gists_url": "https://api.github.com/users/errfree/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/errfree/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/errfree/subscriptions",
    "organizations_url": "https://api.github.com/users/errfree/orgs",
    "repos_url": "https://api.github.com/users/errfree/repos",
    "events_url": "https://api.github.com/users/errfree/events{/privacy}",
    "received_events_url": "https://api.github.com/users/errfree/received_events",
    "type": "Organization",
    "site_admin": false
  },
  {
    "login": "mojodna",
    "id": 45,
    "node_id": "MDQ6VXNlcjQ1",
    "avatar_url": "https://avatars.githubusercontent.com/u/45?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mojodna",
    "html_url": "https://github.com/mojodna",
    "followers_url": "https://api.github.com/users/mojodna/followers",
    "following_url": "https://api.github.com/users/mojodna/following{/other_user}",
    "gists_url": "https://api.github.com/users/mojodna/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mojodna/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mojodna/subscriptions",
    "organizations_url": "https://api.github.com/users/mojodna/orgs",
    "repos_url": "https://api.github.com/users/mojodna/repos",
    "events_url": "https://api.github.com/users/mojodna/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mojodna/received_events",
    "type": "User",
    "site_admin": false
  },
  {
    "login": "bmizerany",
    "id": 46,
    "node_id": "MDQ6VXNlcjQ2",
    "avatar_url": "https://avatars.githubusercontent.com/u/46?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/bmizerany",
    "html_url": "https://github.com/bmizerany",
    "followers_url": "https://api.github.com/users/bmizerany/followers",
    "following_url": "https://api.github.com/users/bmizerany/following{/other_user}",
    "gists_url": "https://api.github.com/users/bmizerany/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/bmizerany/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/bmizerany/subscriptions",
    "organizations_url": "https://api.github.com/users/bmizerany/orgs",
    "repos_url": "https://api.github.com/users/bmizerany/repos",
    "events_url": "https://api.github.com/users/bmizerany/events{/privacy}",
    "received_events_url": "https://api.github.com/users/bmizerany/received_events",
    "type": "User",
    "site_admin": false
  }]


  constructor() { }

  ngOnInit(): void {
  }

}
